default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: peanut_development

test:
  <<: *default
  database: peanut_test

production:
  <<: *default
  database: peanut_production
  username: peanut
  password: <%= ENV['PEANUT_DATABASE_PASSWORD'] %>
